### ISSUE TITLE
CMake Error: CMake can not determine linker language for target: UICatalog

### ISSUE THREAD

**Issue by ddanilyuk** [compnerd/swift-win32#157] opened 2020-09-26 23:01 UTC
Hello. I have build error with your example app (UICatalog).

I have installed all components (Swift and VS) from [https://swift.org/getting-started/#installing-swift](Installing swift)
I have installed CMake and ninja from official sites.

Here is my ERROR.
Have you any ideas what I am doing wrong?

<img width="1303" alt="Screenshot 2020-09-27 at 01 55 13" src="https://user-images.githubusercontent.com/26975779/94351716-c19db580-0064-11eb-9516-04b32f437a22.png">

**Comment by compnerd** [comment] 2020-09-27 01:26
You are executing the command from the wrong directory.  You must be in the top level of the project (swift-win32).

**Comment by ddanilyuk** [comment] 2020-09-27 15:09
I changed directory and I have next error.

<img width="1561" alt="Screenshot 2020-09-27 at 18 01 11" src="https://user-images.githubusercontent.com/26975779/94368184-87c3c200-00eb-11eb-8aa0-71218c992684.png">

If I delete TextField.swift and all where it was used, building complete and UICatalog started. 

But after this I have another problem: After closing UICatalog, File Explorer starts not responding at all. And after that, a complete reboot is needed. Have you any ideas how to fix this problems?

**Comment by OmerFlame** [comment] 2020-09-27 15:39
Getting stuck on this issue as well. @compnerd can you please help us?

**Comment by compnerd** [comment] 2020-09-27 17:31
There are two different issues there:
1. Unable to build TextView
2. Explorer hang

I think that 2 is directly related to 1.  The hang is likely some subclassing gone awry, and the message loop just trying to recover.  I think that it would only be interesting to investigate after 1 is resolved.

Fortunately, the first issue is much easier to contend with. It seems that `PARAFORMAT` is missing in the Windows SDK.  That is odd, because that definition has been there for a long while.  It is more likely that the modulemap for the WinSDK (winsdk.modulemap) needs to be newer.  Unfortunately, that only leaves two reasonable avenues of approach:
1. update to a snapshot instead of the 5.3 release
2. checkout an older revision of the tree.  This of course would lose a bunch of recent work.  I expect that 7f82dc2b33c3631fe36fe0170d4d3222a4b8bfb6 should be a good revision for that.
The third option is no longer viable (fetching the lastest modulemap from apple/swift) as the rebranching for the latest LLVM has  significant improvements to the module structure that we are now using.

The progress in the project unfortunately does require the newer snapshots as I tend to just fix the issues in the toolchain if I run into them rather than work around them to improve both the codebase here as well as the toolchain.

**Comment by jkarwisch** [comment] 2020-09-27 19:51
I had the same issue with building TextView. After updating to the latest snapshot of 5.3, and it compiled with only a depreciation warning. Ran UICatalog and it appeared ok, but after closing the app, Explorer is hung and will have to reboot.

**Comment by compnerd** [comment] 2020-09-27 20:16
@jkarwisch interesting, I've not seen any of the explorer hand in quite some time, and even then only when I was actually working on specific controls.  Would you be able to attach a debugger to explorer and see what exactly is responsible for the hang?  I am unable to reproduce this.  However, I am running the dev channel of Windows, so it could be that there is an issue that doesn't appear due to the newer Windows userspace.

**Comment by jkarwisch** [comment] 2020-09-27 22:35
Not familiar with debugging on windows, but attached the VS 2019 debugger on Explorer and got this (the third line appeared after awhile):

The thread 0x29c has exited with code 0 (0x0).
The thread 0x32c has exited with code 0 (0x0).
Exception thrown at 0x00007FFC51403E49 (KernelBase.dll) in explorer.exe: 0x800706BA: The RPC server is unavailable.

**Comment by compnerd** [comment] 2020-09-27 22:44
Hmm, I think that is an explorer specific thing, where the COM endpoint failed to connect.  It doesn't really help identify why the explorer message loop is getting impacted by the application.  I suppose that one approach which is really time consuming but would at least help narrow down things is to remove all the controls from UICatalog and start adding them back in one at a time until explorer hangs.  BTW, you should be able to kill and restart explorer rather than restarting the machine.

**Comment by jkarwisch** [comment] 2020-09-27 22:56
I will try doing that when I get a chance. When Explorer hangs, I can't even launch task manager. Start menu is unresponsive
 and even VS 2019 starts having problems. Windows 10 is running on a VMware VM, so not much of a big deal rebooting it.

**Comment by compnerd** [comment] 2020-09-27 23:13
ctrl-shift-esc should still work and give you task manager which will allow you to terminate and start explorer.  However, restarting the VM is also an option if you don't mind that.

**Comment by compnerd** [comment] 2020-10-01 16:56
I am going to close this for now as I believe that this has been fixed thanks to @GunGraveKoga.  #173 has been merged and that should fix the explorer issue.

**Closed by compnerd** 2020-10-01 16:56 UTC
Labels: bug
