### ISSUE TITLE
the package manifest at '\Package@swift-5.8.swift' cannot be accessed symlinks not supported

### ISSUE THREAD

**Issue by nileshyadavme** [compnerd/swift-win32#783] opened 2024-08-08 12:15 UTC
error: the package manifest at '\Package@swift-5.8.swift' cannot be accessed (InternalError(description: "Internal error. Please file a bug at https://github.com/apple/swift-package-manager/issues with this info. symlinks not supported"))
----SYSTEM INFORMATION----
- OS : Window 11
- Version:	10.0.22631 Build 22631
- Swift version 5.10.1 (swift-5.10.1-RELEASE) Target: x86_64-unknown-windows-msvc

### Here is a Screenshot of package.swift.
![Screenshot 2024-08-08 174141](https://github.com/user-attachments/assets/d6d66873-dfbf-4a7a-9185-0c8ae7558001)

**Comment by compnerd** [comment] 2024-08-08 13:24
I'll close this as a duplicate later. The problem is that symbolic links are not enabled and you've not followed the instructions to enable developer mode or grant yourself the `SeCreateSymbolicLinkPrivelege` privilege. In order to test and maintain compatibility with older Swift releases, I'm using symbolic links to avoid duplicating the package manifest. SPM also generates symbolic links by default so this is really not an unreasonable ask for developers to enable.

**Comment by compnerd** [comment] 2024-08-08 15:28
Duplicate of: #771

**Closed by compnerd** 2024-08-08 15:28 UTC
